version: '3.8'

services:
  qudiffusive-web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env.local
    environment:
      - ENVIRONMENT=production
      - HOST=0.0.0.0
      - PORT=8080
    volumes:
      - ./model_cache:/app/model_cache
      - ./logs:/app/logs
      - ./data:/app/data
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - qudiffusive-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - qudiffusive-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.local.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      qudiffusive-web:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - qudiffusive-network

volumes:
  redis_data:

networks:
  qudiffusive-network:
    driver: bridge
